apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-cicd
  template:
    metadata:
      labels:
        app: springboot-cicd
    spec:
      containers:
        - name: springboot-cicd
          image: sandhyadocker11/springboot-cicd:latest
          ports:
            - containerPort: 8080