name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Maven Build
        run: mvn clean package

      - name: Trivy File System Scan
        run: trivy fs .

      - name: Build Docker Image
        run: docker build -t springboot-cicd .